### PR TITLE
run_vm.sh: add new argument options and small improvement (WIP)

### PR DESCRIPTION
**Pull request by memnoth**
Add following options
1. -numa   : enable NUMA mode for single vmachine.
2. -start  : Start number of vCPU at a real machine.
3. -iplist : IP list which inter-connect'ed between machines
             by infiniband

Also, use $(expr `nproc` / 2) to get the correct number of physical
CPUs in real machines even though they are on the hyper-threading.
This is much easier to calculate how many CPUs we would like to attach
to each QEMU instance than take the number of real cores.

For instance, we have 2 real machine, m1 and m2, connected by infiniband
and each machine has 16 cores (HT). Each one should take 8 cores for -smp
option and vCPU must be started at 0 and 4 respectively with -local-cpu
4 option.

Be careful that this patch is only for default options of test-bed,
if any of you want to change the options in different environment.
Please use arguments.

### CODE REVIEW

**Comment by memnoth** [comment]
This is actually trying to merge two versions, `run_vm` and `run_gvm` into one file like all-in-one.
Feel free to comment !

**Comment by ChoKyuWon** [comment]
Current method, ``grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}'`` get a correct number of the physical core of the machine, even if hyperthreading is on. But in your method,``expr nproc / 2``returns wrong physical core if hyperthreading is off.

Here are some examples of the result of the command:

Desktop1: Hyperthreading is disabled
```
$ lscpu
CPU(s):              6
On-line CPU(s) list: 0-5
Thread(s) per core:  1
Core(s) per socket:  6
Socket(s):           1
$ grep ^cpu\\scores /proc/cpuinfo
cpu cores       : 6
$ nproc
6
```

Server1: Hyperthreading is enabled
```
$ lscpu
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       1
$ grep ^cpu\\scores /proc/cpuinfo
cpu cores       : 64
$ nproc
128
```

So your method and current method are both worked in hyperthread-enable environment, but your method does not work in hyperthread-disabled environment.

**Comment by YWHyuk** [comment]
Oh this is what am I doing now. what a coincidence!
  
```bash
if [ "$NUMA_MODE" = true ]; then
    COMMAND+="-object memory-backend-ram,size=$NODE_SIZE,id=ram0 "
    COMMAND+="-numa node,nodeid=0,cpus=0-$((NR_CPU/2 - 1)),memdev=ram0 "
    COMMAND+="-object memory-backend-ram,size=$NODE_SIZE,id=ram1 "
    COMMAND+="-numa node,nodeid=1,cpus=$((NR_CPU/2))-$((NR_CPU-1)),memdev=ram1 "
fi

COMMAND+="-device e1000,netdev=net0 "
COMMAND+="-netdev user,id=net0,hostfwd=tcp::5556-:22 " <------------ 1)

$COMMAND
if [ "$NUMA_MODE" = false ]; then
    if [ "$START_VCPU" == "0" ]; then
        COMMAND+="-redir tcp:5556::22 " <--------------------------- 2)
    fi
    COMMAND+="-local-cpu $((NR_CPU/2)),start=${START_VCPU},iplist=${IPLIST} "
fi
```
When NUMA_MODE is false and START_VCPU is 0, It seem like that  same port is used twice.
How about this?

```bash
if [ "$NUMA_MODE" = true ]; then
    COMMAND+="-object memory-backend-ram,size=$NODE_SIZE,id=ram0 "
    COMMAND+="-numa node,nodeid=0,cpus=0-$((NR_CPU/2 - 1)),memdev=ram0 "
    COMMAND+="-object memory-backend-ram,size=$NODE_SIZE,id=ram1 "
    COMMAND+="-numa node,nodeid=1,cpus=$((NR_CPU/2))-$((NR_CPU-1)),memdev=ram1 "
    
    COMMAND+="-device e1000,netdev=net0 "
    COMMAND+="-netdev user,id=net0,hostfwd=tcp::5556-:22 "
else
    if [ "$START_VCPU" == "0" ]; then
        COMMAND+="-redir tcp:5556::22 " <--------------------------- 2)
    fi
    COMMAND+="-local-cpu $((NR_CPU/2)),start=${START_VCPU},iplist=${IPLIST} "
fi
```

Also iplist should be enclosed in quotation marks. ex) "10.10.20.14 10.10.20.16"
But it's debug output like this
```bash
$ ./run_gvm2.sh -c 8 -m 8192 -s 0 -i "10.10.20.53 10.10.20.54"
qemu-system-x86_64 ...  -local-cpu 4,start=0,iplist=10.10.20.53 10.10.20.54
```
My suggestion is like this
```diff
if [ "$NUMA_MODE" = false ]; then
    if [ "$START_VCPU" == "0" ]; then
        COMMAND+="-redir tcp:5556::22 "
    fi
-     COMMAND+="-local-cpu $((NR_CPU/2)),start=${START_VCPU},iplist=${IPLIST} "
+    $COMMAND -local-cpu $((NR_CPU/2)),start=${START_VCPU},iplist="${IPLIST}"

fi
```

**Comment by YWHyuk** [comment]
Hi, @ChoKyuWon 
> Current method, `grep ^cpu\\scores /proc/cpuinfo | uniq | awk '{print $4}'` get a correct number of the physical core of the machine, even if hyperthreading is on. But in your method,`expr nproc / 2`returns wrong physical core if hyperthreading is off.

Actually, It works correctly on the single socket😭

**Comment by ChoKyuWon** [comment]
@YWHyuk Oh you're right. I foud my another server is hyperthread-disabled and use two socket. Here is some result that I run the commands:
```
$ lscpu
CPU(s):                          64
On-line CPU(s) list:             0-31
Off-line CPU(s) list:            32-63
Thread(s) per core:              1
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    2
$ grep ^cpu\\scores /proc/cpuinfo | uniq | awk '{print $4}'
16
$ nproc
32
```
I see  the problem, but ```nproc/2``` will not be a solution.

**Comment by YWHyuk** [comment]
@ChoKyuWon 
> I see the problem, but `nproc/2` will not be a solution.
Yes, any good ideas?

**Comment by ChoKyuWon** [comment]
@YWHyuk 
``` expr `nproc` / `lscpu | grep "Thread(s) per core" | uniq | awk '{print $4}'` ``` will work.

**Comment by YWHyuk** [comment]
@memnoth 
> `` expr `nproc` / `lscpu | grep "Thread(s) per core" | uniq | awk '{print $4}' `` will work.

It looks nice👍

**Comment by ChoKyuWon** [comment]
@memnoth 
I create a new pull request on our repository. I guess if you merge it, my commit will be shown to this pull request automatically, but not sure.

**Comment by memnoth** [comment]
@ChoKyuWon @YWHyuk 
Thank you for the reviews!

Here is a reason why I picked this, $(expr \`nproc\` / 2).

As QEMU perspective, it doesn't care how many physical cores are existed and whether they are on hyper-threading or not. It might care about only how many virtual cpus it will take in -smp option. With `nproc`, we don't need to care about hardware-level CPUs that "this machine has 2 sockets, 32 cores and hyper-threading is on" or something like that, only care about user-level CPU numbers.

However, we don't actually want to attach all the number of user-level CPUs to QEMU instance, so `nproc / 2` would be nice number for QEMU as my opinion. According to this, 16 user-level cores would be half as 8 which is enough for test-bed no matter it's on hyper-threading or not and 32 would be 16.

My point is we don't have to care those hardware-level CPU numbers to run QEMU. I am not sure mine is better or that might be wrong. Let me know you guys' thought, I just try looking for better ways and feel free comment on the reason as well.

-----

One tip for you guys might already know
As @ChoKyuWon has made a PR in my personal forked one, it's not good approach. So there are 2 ways to do what you'd like to do.

1. Make your own PR separated which change the expression, then I go pulling again and rebase my PR.
2. I take your change in this commit and put you on `signed-off` member. This means "Sign-off is a line at the end of the commit message which certifies who is the author of the commit.". This is how kernel community work together. I prefer this one, because make less commits, but say work together in one commit.

Happy Hacking!

**Comment by YWHyuk** [comment]
Hi @memnoth  
> My point is we don't have to care those hardware-level CPU numbers to run QEMU. I am not sure mine is better or that might be wrong. Let me know you guys' thought, I just try looking for better ways and feel free comment on the reason as well.

Yes, it is just **default** value of vCPU and it  a kind of **policy**. Anyway, both are better than previous one😉
---
*P.S.*
Can you clean up this line? I put it for debug but still there..
Thanks

```bash
function parse_args
{
  # named args
  while [ "$1" != "" ]; do
      echo "$1" <---------- here
}
```

**Comment by YWHyuk** [comment]
@memnoth 
I tested it but there is still problem in parsing iplist
```bash
$ ./run_gvm2.sh -c 8 -m 8192 -s 0 -i "10.10.20.53 10.10.20.54"
qemu-system-x86_64 -enable-kvm -hda bionic-server-cloudimg-amd64.img -hdb user-data.img -cpu host,-kvm-asyncpf -machine kernel-irqchip=off -smp 8 -m 8192 -nographic -serial mon:stdio -monitor telnet:127.0.0.1:1234,server,nowait -redir tcp:5557::22 -local-cpu 4,start=0,iplist="10.10.20.53 10.10.20.54"
qemu-system-x86_64: -redir tcp:5557::22: The -redir option is deprecated. Please use '-netdev user,hostfwd=...' instead.
qemu-system-x86_64: -local-cpu 4,start=0,iplist="10.10.20.53: iplist parse failed
```
It parsed that iplist's value is `"10.10.20.53`

**Comment by memnoth** [comment]
@YWHyuk Fixed it

**Comment by ChoKyuWon** [comment]
@memnoth
I'm confused because of the comment on the shell file,
> Default NR_CPU is number of physical cpu

So I suggest ``expr `nproc` / `lscpu | grep "Thread(s) per core" | uniq | awk '{print $4}'``, but as I understand is right, your intention is just set a **reasonable** number of vCPU as default value, right?

I agree on @YWHyuk, It's problem of policy, and there's no forced value. I think there're some way to set the policy:

1. As comment, set ``NR_CPU`` as physical core number. This can be done by ``NR_CPU=$(expr `nproc` / `lscpu | grep "Thread(s) per core" | uniq | awk '{print $4}')``
2. Attach half of cores to qemu, it can be done by ``NR_CPU=$(expr `nproc` / 2)``
3. Or we can just attach all cores to qemu. This can be done by ``NR_CPU=`nproc` ``

I don't know why the original command is set default value of ``NR_CPU`` as physical core number, so I think we need to choose 1 or 3. Because it's **DEFAULT** value, so I think default value should be all number of cores, or just the number of physical cores(for some reason that I don't know).  If users want only half of vCPUs are allocated to qemu, they can use the ``-c, --cpu_nr`` option.

<hr>

Thanks for the tips. I'm not familiar with the open-source community culture, so that's why my approach is not good.
I also agree with the second way, add my name on the ``signed-off`` member makes more sense.

**Comment by ChoKyuWon** [comment]
@memnoth 
Can you explain why 
```sh
if [ "$NUMA_MODE" = true ]; then
    COMMAND+="-object memory-backend-ram,size=$NODE_SIZE,id=ram0 "
    COMMAND+="-numa node,nodeid=0,cpus=0-$((NR_CPU/2 - 1)),memdev=ram0 "
    COMMAND+="-object memory-backend-ram,size=$NODE_SIZE,id=ram1 "
    COMMAND+="-numa node,nodeid=1,cpus=$((NR_CPU/2))-$((NR_CPU-1)),memdev=ram1 "
    
    COMMAND+="-device e1000,netdev=net0 "
    COMMAND+="-netdev user,id=net0,hostfwd=tcp::5556-:22 " --------------------------------1)
else
    if [ "$START_VCPU" == "0" ]; then
        COMMAND+="-redir tcp:5556::22 " ----------------------------------------------------- 2)
    fi
    COMMAND+="-local-cpu $((NR_CPU/2)),start=${START_VCPU},iplist=${IPLIST} "
fi
```
As my knowledge, 1) and 2) are doing completely the same work, right? but in recent qemu, ``--redir`` is deprecated so we need to replace it to ``--device`` and ``--netdev`` option.

How about this?:
```sh
NETWORK_COMMAND+="-device e1000,netdev=net0 "
NETWORK_COMMAND+="-netdev user,id=net0,hostfwd=tcp::5556-:22 "

if [ "$NUMA_MODE" = true ]; then
    COMMAND+="-object memory-backend-ram,size=$NODE_SIZE,id=ram0 "
    COMMAND+="-numa node,nodeid=0,cpus=0-$((NR_CPU/2 - 1)),memdev=ram0 "
    COMMAND+="-object memory-backend-ram,size=$NODE_SIZE,id=ram1 "
    COMMAND+="-numa node,nodeid=1,cpus=$((NR_CPU/2))-$((NR_CPU-1)),memdev=ram1 "
    
    COMMAND+=$NETWORK_COMMAND
else
    if [ "$START_VCPU" == "0" ]; then
        COMMAND+=$NETWORK_COMMAND
    fi
    COMMAND+="-local-cpu $((NR_CPU/2)),start=${START_VCPU},iplist=${IPLIST} "
fi
```

And can you explain more detail about why this script attaches the network command only when START_VCPU is 0?

Thanks!

**Pull request merged**
